
FROM node:18.18-alpine3.17 as build

WORKDIR /usr/src/app

COPY . .

RUN npm install --force

RUN npm run build

FROM nginx:1.25.3-alpine-slim

COPY default.conf /etc/nginx/conf.default

COPY --from=build /usr/src/app/dist/frontend /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
